Repository mobilecoinfoundation/mobilecoin, pull requests merged in 2020-04, with the labels that each got.

#65 Production enclave path update
  consensus/service/BUILD.md
  mobilecoind/README.md
  mobilecoind/clients/python/start-testnet-mobilecoind.sh
  start-testnet-client.sh
Labels: testnet

#66 Python protobuf api only accepts kwargs
  mobilecoind/clients/python/mob_client.py
Labels: testnet

#67 add testnet instructions
  README.md
  TESTNET.md
Labels: testnet

#62 add timestamps to balance check display
  Cargo.lock
  testnet-client/Cargo.toml
  testnet-client/src/main.rs
Labels: next-release, testnet

#102 Improve client experience during ledger catchup
  connection/test-utils/src/blockchain.rs
  ledger/sync/src/ledger_sync_service_thread.rs
  ledger/sync/src/network_state_trait.rs
  ledger/sync/src/polling_network_state.rs
  ledger/sync/src/scp_network_state.rs
  mobilecoind/api/proto/mobilecoind_api.proto
  mobilecoind/src/bin/main.rs
  mobilecoind/src/service.rs
  mobilecoind/src/test_utils.rs
  testnet-client/src/main.rs
Labels: next-release

#88 LedgerDB: Store `BlockSignature` as proto-encoded instead of cbor-encoded
  consensus/api/src/conversions.rs
  crypto/keys/src/ed25519.rs
  ledger/db/src/lib.rs
  transaction/core/src/blockchain/block_signature.rs
Labels: next-release

#98 MC-1340 Removes fee output from range proof, finer-grained errors
  consensus/api/src/conversions.rs
  consensus/service/src/validators.rs
  transaction/core/src/constants.rs
  transaction/core/src/ring_signature/error.rs
  transaction/core/src/ring_signature/mod.rs
  transaction/core/src/ring_signature/rct_bulletproofs.rs
  transaction/core/src/tx.rs
  transaction/core/src/validation/error.rs
  transaction/core/src/validation/mod.rs
  transaction/core/src/validation/validate.rs
  transaction/std/src/transaction_builder.rs
Labels: next-release

#106 More serde->prost changes in Ledger + introducing metadata versioning storage
  ledger/db/src/error.rs
  ledger/db/src/lib.rs
  ledger/db/src/metadata.rs
  ledger/db/src/tx_out_store.rs
  tools/local-network/bootstrap.sh
Labels: next-release

#95 Add rpc response type to allow unknown peers without error
  Cargo.lock
  consensus/api/proto/consensus_peer.proto
  consensus/service/src/peer_api_service.rs
  peers/src/connection.rs
  peers/src/sync.rs
  peers/src/threaded_broadcaster.rs
  peers/src/traits.rs
  peers/test-utils/Cargo.toml
  peers/test-utils/src/lib.rs
Labels: next-release

#104 Add cumulative txo count to the block header
  consensus/api/proto/blockchain.proto
  consensus/api/src/conversions.rs
  consensus/enclave/impl/src/lib.rs
  consensus/enclave/mock/src/lib.rs
  consensus/service/src/blockchain_api_service.rs
  ledger/db/src/lib.rs
  ledger/db/src/test_utils/mock_ledger.rs
  ledger/sync/src/ledger_sync_service.rs
  ledger/sync/src/test_app/main.rs
  mobilecoind/src/service.rs
  mobilecoind/src/test_utils.rs
  transaction/core/src/blockchain/block.rs
  transaction/core/test-utils/src/lib.rs
  transaction/core/tests/blockchain.rs
  util/generate-sample-ledger/src/lib.rs
Labels: next-release
