Repository mobilecoinfoundation/mobilecoin, pull requests merged in 2022-06, with the labels that each got.

#2097 Implement bare bones FogViewRouterAPI server + client
  Cargo.lock
  fog/api/proto/view.proto
  fog/uri/src/lib.rs
  fog/view/connection/Cargo.toml
  fog/view/connection/src/bin/router_client.rs
  fog/view/connection/src/fog_view_router_client.rs
  fog/view/connection/src/lib.rs
  fog/view/server/src/bin/router.rs
  fog/view/server/src/config.rs
  fog/view/server/src/fog_view_router_server.rs
  fog/view/server/src/fog_view_router_service.rs
  fog/view/server/src/lib.rs
Labels: fog-view

#1693 Add GitHub Workflows for CI & build checks
  .config/nextest.toml
  .github/actions/check-dirty-git/action.yml
  .github/actions/run-mc-tests/action.yml
  .github/actions/sccache/action.yml
  .github/actions/setup-rust/action.yml
  .github/actions/upload-core-dumps/action.yml
  .github/dependabot.yml
  .github/workflows/android-bindings-dispatch.yml
  .github/workflows/build_lint.yml
  .github/workflows/ci.yml
  .gitignore
  Brewfile
  Cargo.toml
  crypto/ring-signature/Cargo.toml
  docker/install_sgx.sh
  fog/distribution/tests/bootstrap.rs
  fog/ingest/server/src/bin/main.rs
  fog/overseer/server/src/bin/main.rs
  fog/report/server/src/bin/main.rs
  fog/sql_recovery_db/src/bin/fog_sql_recovery_db_migrations.rs
  fog/sql_recovery_db/src/test_utils.rs
  fog/view/server/src/bin/main.rs
  mobilecoind/src/service.rs
  tools/fog-local-network/fog_conformance_tests.py
  tools/fog-local-network/fog_local_network.py
  tools/fog-local-network/local_fog.py
  tools/local-network/local_network.py
  util/generate-sample-ledger/tests/bootstrap.rs
  util/grpc/src/grpcio_extensions.rs
Labels: ci

#2121 Tidy up BlockVersion method docs
  transaction/types/src/block_version.rs
Labels: documentation

#2115 Implement create_multi_view_query_data API for Fog View Router
  Cargo.lock
  fog/uri/src/lib.rs
  fog/view/enclave/api/Cargo.toml
  fog/view/enclave/api/src/lib.rs
  fog/view/enclave/impl/Cargo.toml
  fog/view/enclave/impl/src/lib.rs
  fog/view/enclave/src/lib.rs
  fog/view/enclave/trusted/Cargo.lock
  fog/view/enclave/trusted/src/lib.rs
  fog/view/server/src/fog_view_router_service.rs
Labels: fog-view

#2125 Improve `VerificationReport` rendering in logs
  attest/core/src/ias/verify.rs
  sgx/report-cache/untrusted/src/lib.rs
Labels: enhancement

#2166 Statically link SQLite
  Cargo.lock
  Cargo.toml
  fog/sql_recovery_db/Cargo.toml
  mint-auditor/Cargo.toml
Labels: build, tech-debt

#2163 Update `mob` to only pull the builder image
  .mobconf
  docker/Dockerfile
  docker/Dockerfile-version
  mob
  tools/update_image.sh
Labels: build, tech-debt

#2171 Update many types' `Debug` rendering to use hexadecimal strings instead of byte arrays
  Cargo.lock
  account-keys/src/identity.rs
  attest/core/Cargo.toml
  attest/core/data/test/quote_ok_str.txt
  attest/core/src/ias/verify.rs
  attest/core/src/lib.rs
  attest/core/src/quote.rs
  attest/core/src/report.rs
  attest/core/src/traits.rs
  attest/verifier/Cargo.toml
  attest/verifier/src/lib.rs
  blockchain/types/Cargo.toml
  blockchain/types/src/block_id.rs
  common/src/node_id.rs
  consensus/enclave/trusted/Cargo.lock
  crypto/keys/src/ed25519.rs
  crypto/keys/src/ristretto.rs
  crypto/keys/src/x25519.rs
  crypto/ring-signature/src/amount/commitment.rs
  crypto/ring-signature/src/amount/compressed_commitment.rs
  crypto/ring-signature/src/ring_signature/curve_scalar.rs
  crypto/ring-signature/src/ring_signature/key_image.rs
  fog/ingest/enclave/trusted/Cargo.lock
  fog/ledger/enclave/trusted/Cargo.lock
  fog/view/enclave/trusted/Cargo.lock
  mobilecoind/src/database_key.rs
  transaction/core/src/memo.rs
  util/repr-bytes/Cargo.toml
  util/repr-bytes/src/lib.rs
Labels: enhancement, logging, rust

#2133 Implement MultiViewStoreQuery API for Fog View
  fog/api/proto/view.proto
  fog/view/server/src/fog_view_service.rs
  fog/view/server/src/server.rs
Labels: fog-view

#2123 Remove CircleCI config
  .circleci/config.yml
Labels: ci

#2193 Make telemetry opt-in
  mobilecoind/src/bin/main.rs
  util/telemetry/src/jaeger.rs
  util/telemetry/src/lib.rs
Labels: enhancement, ci, tech-debt, rust, performance, consensus, fog-view, fog-ledger, fog-ingest, mobilecoind
