Repository mobilecoinfoundation/mobilecoin, pull requests merged in 2022-11, with the labels that each got.

#2525 Add `mc_core` package with new no_std compatible key / account types and logic
  Cargo.lock
  Cargo.toml
  account-keys/Cargo.toml
  account-keys/slip10/Cargo.toml
  account-keys/slip10/README.md
  account-keys/slip10/examples/make-random-key.rs
  account-keys/slip10/examples/pubkey-from-mnemonic.rs
  account-keys/slip10/src/lib.rs
  account-keys/src/account_keys.rs
  account-keys/src/domain_separators.rs
  account-keys/types/src/traits.rs
  consensus/enclave/trusted/Cargo.lock
  core/Cargo.toml
  core/README.md
  core/examples/slip10.rs
  core/src/consts.rs
  core/src/lib.rs
  core/src/protos.rs
  core/src/slip10/mod.rs
  core/src/subaddress.rs
  core/tests/README.md
  core/tests/mnemonic2slip.py
  core/tests/slip10_key.json
  core/tests/slip10_mnemonic.json
  core/tests/slip2ristrettovec.py
  core/tests/testvectors.py
  core/types/Cargo.toml
  core/types/src/account.rs
  core/types/src/keys.rs
  core/types/src/lib.rs
  core/types/src/markers.rs
  fog/ingest/enclave/trusted/Cargo.lock
  fog/ledger/enclave/trusted/Cargo.lock
  fog/view/enclave/trusted/Cargo.lock
  mobilecoind/Cargo.toml
  mobilecoind/src/service.rs
  test-vectors/account-keys/Cargo.toml
  test-vectors/account-keys/build.rs
  util/keyfile/Cargo.toml
  util/keyfile/src/error.rs
  util/keyfile/src/keygen.rs
  util/keyfile/src/lib.rs
  util/keyfile/src/mnemonic_acct.rs
Labels: tech-debt, rust

#2683 Add TxSummary object and incorporate it into MLSAG signing digest
  api/proto/external.proto
  api/src/convert/signing_data.rs
  transaction/core/src/domain_separators.rs
  transaction/core/src/input_rules.rs
  transaction/core/src/lib.rs
  transaction/core/src/revealed_tx_out.rs
  transaction/core/src/ring_ct/mod.rs
  transaction/core/src/ring_ct/rct_bulletproofs.rs
  transaction/core/src/ring_ct/signing_digest.rs
  transaction/core/src/tx.rs
  transaction/core/src/tx_summary.rs
  transaction/core/src/validation/validate.rs
  transaction/extra/src/unsigned_tx.rs
  transaction/types/src/block_version.rs
Labels: enhancement, blocks-v4.0.0, transaction-core

#2584 allow specifying a fog hint when minting
  .github/workflows/ci.yml
  Cargo.lock
  api/proto/external.proto
  api/src/convert/mint_tx.rs
  consensus/api/proto/consensus_client.proto
  consensus/api/src/conversions.rs
  consensus/enclave/impl/src/lib.rs
  consensus/mint-client/Cargo.toml
  consensus/mint-client/src/bin/main.rs
  consensus/mint-client/src/config.rs
  consensus/mint-client/src/fog.rs
  consensus/mint-client/src/lib.rs
  consensus/tool/src/main.rs
  fog/sample-paykit/src/cached_tx_data/mod.rs
  fog/sample-paykit/src/client.rs
  fog/test-client/src/test_client.rs
  tools/fog-local-network/local_fog.py
  transaction/core/src/mint/tx.rs
  transaction/core/src/mint/validation/error.rs
  transaction/core/src/mint/validation/tx.rs
  transaction/core/test-utils/src/mint.rs
  transaction/types/src/block_version.rs
Labels: blocks-v4.0.0, transaction-core

#2809 Make the TxSummary include a digest of input rules, per discussion
  transaction/core/src/input_rules.rs
  transaction/core/src/tx_summary.rs
Labels: blocks-v4.0.0

#2792 [TOB-5] move FeeMap into mc-transaction-core so it could get used inside the transaction builder
  connection/test-utils/src/blockchain.rs
  consensus/enclave/api/src/config.rs
  consensus/enclave/api/src/error.rs
  consensus/enclave/api/src/lib.rs
  consensus/enclave/impl/src/lib.rs
  consensus/enclave/src/lib.rs
  consensus/enclave/tests/enclave_api_tests.rs
  consensus/enclave/tests/graceful_teardown.rs
  consensus/service/config/src/error.rs
  consensus/service/config/src/lib.rs
  consensus/service/config/src/tokens.rs
  consensus/service/src/api/blockchain_api_service.rs
  mobilecoind/src/test_utils.rs
  transaction/core/src/fee_map.rs
  transaction/core/src/lib.rs
Labels: blocks-v4.0.0

#2793 [TOB-5] add fee_map_digest to Tx
  api/proto/external.proto
  api/src/convert/tx.rs
  consensus/api/proto/consensus_common.proto
  consensus/enclave/api/src/config.rs
  consensus/enclave/api/src/error.rs
  consensus/enclave/impl/src/lib.rs
  consensus/enclave/tests/enclave_api_tests.rs
  consensus/service/src/api/client_api_service.rs
  consensus/service/src/api/grpc_error.rs
  fog/sample-paykit/src/client.rs
  fog/sample-paykit/src/error.rs
  fog/test-client/src/test_client.rs
  transaction/builder/src/transaction_builder.rs
  transaction/core/src/fee_map.rs
  transaction/core/src/tx.rs
  transaction/extra/src/unsigned_tx.rs
Labels: blocks-v4.0.0

#2814 MCIP 57 update ring uniqueness requirements for SCIs
  transaction/core/src/validation/validate.rs
  transaction/core/tests/validation.rs
Labels: blocks-v4.0.0

#2794 [TOB-5] mobilecoind: plumb fee_map into transaction builder
  mobilecoind/src/error.rs
  mobilecoind/src/payments.rs
Labels: blocks-v4.0.0

#2732 add nesting support to SignerSet
  .internal-ci/test/minting-config-tx-test.sh
  api/proto/external.proto
  api/src/convert/ed25519_multisig.rs
  consensus/enclave/api/src/governors_map.rs
  consensus/mint-client/src/printers.rs
  consensus/service/config/src/tokens.rs
  crypto/multisig/src/lib.rs
  transaction/core/src/mint/validation/config.rs
Labels: blocks-v4.0.0

#2734 remove toml parsing for the tokens config file in preparation for nested multisigs (toml doesnt handle nesting very well)
  Cargo.lock
  consensus/mint-client/Cargo.toml
  consensus/mint-client/src/bin/main.rs
  consensus/mint-client/src/config.rs
  consensus/service/config/src/tokens.rs
Labels: blocks-v4.0.0

#2736 Change governors/tokens.json to support multi signers
  .github/workflows/mobilecoin-dev-cd.yaml
  .github/workflows/mobilecoin-dispatch-dev-deploy.yaml
  .github/workflows/mobilecoin-dispatch-dev-update-consensus.yaml
  .github/workflows/mobilecoin-workflow-dev-deploy.yaml
  .github/workflows/mobilecoin-workflow-dev-setup-environment.yaml
  .github/workflows/mobilecoin-workflow-dev-update-consensus.yaml
  .internal-ci/test/minting-config-tx-test.sh
  .internal-ci/util/generate_tokens_config.sh
  .internal-ci/util/tokens.v1.base.json
  .internal-ci/util/tokens.v2.base.json
  Cargo.lock
  consensus/service/config/Cargo.toml
  consensus/service/config/src/error.rs
  consensus/service/config/src/lib.rs
  consensus/service/config/src/signer_identity.rs
  consensus/service/config/src/tokens.rs
  consensus/service/src/api/client_api_service.rs
  consensus/service/src/api/grpc_error.rs
  tools/local-network/local_network.py
Labels: blocks-v4.0.0

#2767 Gate the usage of nested multisigs on a block version change
  .internal-ci/util/tokens.v2.base.json
  consensus/enclave/api/src/config.rs
  consensus/enclave/api/src/error.rs
  transaction/core/src/mint/validation/config.rs
  transaction/types/src/block_version.rs
Labels: blocks-v4.0.0

#2784 Add enclave form_block tests for nested multisigs to ensure end-to-end block forming behaves as expected.
  consensus/enclave/impl/src/lib.rs
Labels: blocks-v4.0.0

#2791 Change mint-client to accept MintConfigTx parameters from a JSON file
  .github/workflows/mobilecoin-dev-cd.yaml
  .github/workflows/mobilecoin-workflow-dev-test.yaml
  .internal-ci/test/minting-config-tx-test.sh
  .internal-ci/test/minting-config-tx.json
  Cargo.lock
  consensus/mint-client/Cargo.toml
  consensus/mint-client/src/bin/main.rs
  consensus/mint-client/src/config.rs
  consensus/mint-client/src/lib.rs
  consensus/mint-client/src/mint_config_tx_file.rs
  tools/local-network/authorize-minters.py
Labels: blocks-v4.0.0
