Repository mobilecoinfoundation/mobilecoin, pull requests merged in 2022-03, with the labels that each got.

#1556 Replace datatest
  Cargo.lock
  Cargo.toml
  account-keys/Cargo.toml
  account-keys/src/account_keys.rs
  account-keys/src/identity.rs
  account-keys/src/lib.rs
  api/Cargo.toml
  api/src/display.rs
  api/src/lib.rs
  test-vectors/README.md
  util/test-vector/Cargo.toml
  util/test-vector/README.md
  util/test-vector/src/lib.rs
  util/test-with-data/Cargo.toml
  util/test-with-data/src/lib.rs
Labels: rust-update, rust

#1575 Add Fog Local Network and Test Client to CI
  .circleci/config.yml
  fog/distribution/src/main.rs
  fog/sample-paykit/src/client.rs
  fog/test-client/src/test_client.rs
  tools/fog-local-network/README.md
  tools/fog-local-network/fog_local_network.py
  tools/local-network/local_network.py
Labels: ci

#1592 Update grpcio to 0.10
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  admin-http-gateway/Cargo.toml
  attest/api/Cargo.toml
  connection/Cargo.toml
  connection/src/credentials.rs
  connection/src/thick.rs
  consensus/api/Cargo.toml
  consensus/service/Cargo.toml
  fog/api/Cargo.toml
  fog/api/src/lib.rs
  fog/distribution/Cargo.toml
  fog/enclave_connection/Cargo.toml
  fog/enclave_connection/src/lib.rs
  fog/ingest/client/Cargo.toml
  fog/ingest/server/Cargo.toml
  fog/ledger/connection/Cargo.toml
  fog/ledger/server/Cargo.toml
  fog/load_testing/Cargo.toml
  fog/overseer/server/Cargo.toml
  fog/report/api/Cargo.toml
  fog/report/cli/Cargo.toml
  fog/report/connection/Cargo.toml
  fog/report/server/Cargo.toml
  fog/sample-paykit/Cargo.toml
  fog/test-client/Cargo.toml
  fog/view/connection/Cargo.toml
  fog/view/load-test/Cargo.toml
  fog/view/server/Cargo.toml
  go-grpc-gateway/testing/Cargo.toml
  ledger/sync/Cargo.toml
  mobilecoind-json/Cargo.toml
  mobilecoind/Cargo.toml
  mobilecoind/api/Cargo.toml
  peers/Cargo.toml
  peers/test-utils/Cargo.toml
  slam/Cargo.toml
  util/build/grpc/Cargo.toml
  util/grpc-admin-tool/Cargo.toml
  util/grpc/Cargo.toml
  util/metrics/Cargo.toml
  watcher/Cargo.toml
Labels: dependencies
