Repository mobilecoinfoundation/mobilecoin, pull requests merged in 2022-05, with the labels that each got.

#1888 Update rust-toolchain to nightly-2022-04-29
  docker/rust-toolchain
  mobilecoind/src/utxo_store.rs
  sgx/types/src/types.rs
  transaction/std/src/memo/macros.rs
Labels: rust, 1.3.0

#1908 Dependency updates (Part 1)
  Cargo.lock
  consensus/enclave/trusted/Cargo.lock
Labels: dependencies

#1912 Upgrade rusoto_s3 from 0.42 to 0.48.
  Cargo.lock
  ledger/distribution/Cargo.toml
  ledger/distribution/src/main.rs
Labels: rust

#1921 Add cargo-sort to the pre-commit hook
  hooks/pre-commit
Labels: ci

#1936 Accomodate Arbitrary Platform Reserved Addresses
  account-keys/src/account_keys.rs
  android-bindings/src/bindings.rs
  fog/sample-paykit/src/client.rs
  libmobilecoin/src/transaction.rs
  mobilecoind/src/payments.rs
  transaction/std/src/change_destination.rs
  transaction/std/src/lib.rs
  transaction/std/src/memo_builder/burn_redemption_memo_builder.rs
  transaction/std/src/memo_builder/mod.rs
  transaction/std/src/memo_builder/rth_memo_builder.rs
  transaction/std/src/reserved_destination.rs
  transaction/std/src/transaction_builder.rs
Labels: 1.3.0

#1953 Add proto schema for GiftCode and rust equivalent object
  api/proto/printable.proto
  api/src/convert/mod.rs
  api/src/convert/tx_out_gift_code.rs
  transaction/core/src/lib.rs
  transaction/core/src/tx_out_gift_code.rs
Labels: enhancement, 1.3.0, protobufs

#1932 Gift Code Memos
  Cargo.lock
  fog/sample-paykit/src/cached_tx_data/memo_handler.rs
  transaction/core/src/memo.rs
  transaction/std/Cargo.toml
  transaction/std/src/memo/gift_code_cancellation.rs
  transaction/std/src/memo/gift_code_funding.rs
  transaction/std/src/memo/gift_code_sender.rs
  transaction/std/src/memo/mod.rs
Labels: 1.3.0

#1968 Update builder_install image
  .circleci/config.yml
  docker/Dockerfile
  docker/Dockerfile-version
  docker/init_debian.sh
  jenkins/build-pod.yaml
Labels: ci

#1931 Fix failures when tests are run in parallel, and DRY up tests that start a fog-ingest server
  Cargo.lock
  consensus/service/src/api/attested_api_service.rs
  consensus/service/src/api/blockchain_api_service.rs
  fog/ingest/client/Cargo.toml
  fog/ingest/client/tests/get_ingress_key_records.rs
  fog/ingest/client/tests/sync_keys_from_remote.rs
  fog/ingest/server/Cargo.toml
  fog/ingest/server/src/controller.rs
  fog/ingest/server/src/worker.rs
  fog/ingest/server/test-utils/Cargo.toml
  fog/ingest/server/test-utils/src/lib.rs
  fog/ingest/server/tests/key_sharing_on_activate.rs
  fog/ingest/server/tests/peer_key_sharing.rs
  fog/ingest/server/tests/sealed_key.rs
  fog/ingest/server/tests/three_node_cluster.rs
  fog/ingest/server/tests/tx_recovery.rs
  fog/ledger/server/tests/connection.rs
  fog/overseer/server/Cargo.toml
  fog/overseer/server/src/bin/main.rs
  fog/overseer/server/src/lib.rs
  fog/overseer/server/src/metrics/counters.rs
  fog/overseer/server/src/metrics/mod.rs
  fog/overseer/server/src/metrics/utils.rs
  fog/overseer/server/src/responses.rs
  fog/overseer/server/src/server.rs
  fog/overseer/server/src/service.rs
  fog/overseer/server/src/worker.rs
  fog/overseer/server/tests/get_ingest_summaries.rs
  fog/overseer/server/tests/inactive_outstanding_key_idle_does_not_have_key.rs
  fog/overseer/server/tests/inactive_outstanding_key_idle_has_key.rs
  fog/overseer/server/tests/one_active_node.rs
  fog/overseer/server/tests/prometheus_produces_metrics.rs
  fog/overseer/server/tests/retired_key_not_outstanding_idles_have_different_keys.rs
  fog/overseer/server/tests/retired_key_not_outstanding_idles_have_same_key.rs
  fog/overseer/server/tests/utils/mod.rs
  fog/view/server/Cargo.toml
  fog/view/server/tests/smoke_tests.rs
  mobilecoind/Cargo.toml
  mobilecoind/src/test_utils.rs
Labels: ci, tech-debt, rust

#1933 Gift Code Memo Builder
  account-keys/src/account_keys.rs
  account-keys/src/lib.rs
  transaction/core/src/memo.rs
  transaction/core/src/tx_error.rs
  transaction/std/src/lib.rs
  transaction/std/src/memo_builder/gift_code_cancellation_memo_builder.rs
  transaction/std/src/memo_builder/gift_code_funding_memo_builder.rs
  transaction/std/src/memo_builder/gift_code_sender_memo_builder.rs
  transaction/std/src/memo_builder/mod.rs
  transaction/std/src/test_utils.rs
  transaction/std/src/transaction_builder.rs
Labels: 1.3.0

#2002 Uprev mbedtls to mc-0.5 in foundation repo.
  Cargo.lock
  Cargo.toml
  consensus/enclave/trusted/Cargo.lock
  consensus/enclave/trusted/Cargo.toml
  fog/ingest/enclave/trusted/Cargo.lock
  fog/ingest/enclave/trusted/Cargo.toml
  fog/ledger/enclave/trusted/Cargo.lock
  fog/ledger/enclave/trusted/Cargo.toml
  fog/view/enclave/trusted/Cargo.lock
  fog/view/enclave/trusted/Cargo.toml
Labels: dependencies

#1917 Remove bigint in favor of primitive-types.
  Cargo.lock
  consensus/scp/Cargo.toml
  consensus/scp/src/slot.rs
  consensus/scp/src/utils.rs
Labels: dependencies

#2006 Cherry-pick updates from master.
  Cargo.lock
  Cargo.toml
  admin-http-gateway/Cargo.toml
  admin-http-gateway/src/main.rs
  consensus/enclave/trusted/Cargo.lock
  consensus/enclave/trusted/Cargo.toml
  consensus/mint-client/Cargo.toml
  consensus/mint-client/src/bin/main.rs
  consensus/mint-client/src/config.rs
  consensus/mint-client/src/lib.rs
  consensus/mint-client/src/printers.rs
  consensus/mint-client/src/tx_file.rs
  consensus/scp/Cargo.toml
  consensus/scp/src/slot.rs
  consensus/scp/src/utils.rs
  fog/ingest/enclave/trusted/Cargo.lock
  fog/ingest/enclave/trusted/Cargo.toml
  fog/ledger/enclave/trusted/Cargo.lock
  fog/ledger/enclave/trusted/Cargo.toml
  fog/overseer/server/Cargo.toml
  fog/overseer/server/src/bin/main.rs
  fog/view/enclave/trusted/Cargo.lock
  fog/view/enclave/trusted/Cargo.toml
  mobilecoind-json/Cargo.toml
  mobilecoind-json/src/bin/main.rs
Labels: dependencies

#2025 fix formatting check in pre-commit
  hooks/pre-commit
Labels: 1.3.0

#2033 improve log messages around double spend test
  fog/test-client/src/test_client.rs
Labels: 1.3.0

#2045 make drain accounts script handle defragmentation errors (#2035)
  mobilecoind/strategies/drain-accounts.py
Labels: 1.2.0

#2041 Add fees to gift code memos
  transaction/core/src/memo.rs
  transaction/core/src/tx_error.rs
  transaction/std/src/memo/gift_code_cancellation.rs
  transaction/std/src/memo/gift_code_funding.rs
  transaction/std/src/memo/gift_code_sender.rs
  transaction/std/src/memo_builder/gift_code_cancellation_memo_builder.rs
  transaction/std/src/memo_builder/gift_code_funding_memo_builder.rs
  transaction/std/src/memo_builder/gift_code_sender_memo_builder.rs
  transaction/std/src/test_utils.rs
Labels: 1.3.0
